# Generated by Django 4.0.4 on 2022-04-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название таблицы')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
            },
        ),
        migrations.CreateModel(
            name='TableRowsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('count', models.IntegerField(default=0, verbose_name='Колличество')),
                ('distance', models.FloatField(default=0.0, verbose_name='Расстояние')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.tablemodel', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Строка',
                'verbose_name_plural': 'Строки',
            },
        ),
    ]
