# Generated by Django 4.0.4 on 2022-04-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerowsmodel',
            name='table',
        ),
        migrations.DeleteModel(
            name='TableModel',
        ),
    ]
